server:
  port: 8012
spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-account-service-seata-service-group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: asp_10010
feign:
  hystrix:
    enabled: true
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapper/*.xml