server:
  port: 8003
spring:
  application:
    name: order-service
  cloud:
    #nacos既可以支持AP友可以支持CP，根据需要进行切换
    #切换的命令为curl -X PUT '$NACOS_SERVER:8848/nacos/v1/ns/operator/swiches?entry=serverMode&value=CP'
    nacos:
      discovery:
        server-addr: localhost:8848
service-url:
  nacos-user-service: http://payment-service