server:
  port: 8003
spring:
  application:
    name: order-service
  cloud:
    #nacos既可以支持AP友可以支持CP，根据需要进行切换
    #切换的命令为curl -X PUT '$NACOS_SERVER:8848/nacos/v1/ns/operator/swiches?entry=serverMode&value=CP'
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8081
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: order-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#激活feign支持sentinel的配置
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

#sentinel
#流控规则
  #资源名：唯一名称，默认请求路径（既可以是Mapping路径，又可以是sentinel Resource的value，当不存在blockHandler，使用自带的Flow Exception）
  #针对来源：Sentinel可以针对调用者进行限流，填写微服务名，默认为default（不区分来源）
  #阈值类型/单机阈值：
     #QPS（每秒钟的请求数量）：当调用该API的QPS达到阈值时，则进行限流
     #线程数:当调用该API的线程数达到阈值时，进行限流,（每次访问允许程序处理的线程数量）
  #是否集群：不需要集群
  #流控模式：先拿到Rest地址
     #直接：API达到限流条件时，直接限流
     #关联：当关联的资源达到阈值时，就限流自己（当与A关联的资源B达到阈值时，就限流A自己，订单 -> 支付）
     #链路：只记录指定链路上的流量（指定资源从入口资源进来的流量，如果达到阈值，就进行限流）【API级别的针对来源】
  #流控效果：
     #快速失败：直接失败，抛出异常，默认显示Blocked By sentinel
     #warm up: 根据codeFactor（冷加载因子默认为3）的值，从阈值 除 codeFactor，经过预热时长才达到设置的QPS阈值，秒杀系统开启的瞬间，并发请求量瞬时较大防止系统崩溃
     #排队等待: 匀速排队，让请求匀速的速度通过，阈值类型必须设置为QPS，否则无效(只允许QPS有)


#降级规则  当资源被降级后，在接下来的降级时间窗口期间内，对该资源的调用都会被自动被熔断（默认行为是抛出DegradeException）
          #sentinel的断路器无 半开 状态的
  #资源名：唯一名称，默认请求路径
  #降级策略
     #RT: 平均响应时间，秒级。平均响应时间 超出阈值 且 在时间窗口期内通过的请求数 >= 5，两个条件同时满足后触发降级
          #窗口期过后关闭断路器，RT最大4900（更大的值需要-Dcsp.sentinel.statistic.max.rt = XXXX才能生效）
     #异常比例：秒级。QPS >= 5且异常的比例（秒级统计）超过阈值时，触发降级。时间窗口期结束后，关闭降级。
     #异常数: 异常数(分钟级)超过阈值时，触发降级；时间窗口结束后，关闭降级。（时间窗口一定要大于等于60秒）


#热点规则  （仅支持QPS）热点就是经常访问的数据，并对其访问进行限制。热点参数限流会统计传入参数的热点参数，并且根据配置的限流阈值和模式，对包含
          #热点参数的资源调用进行限流，热点参数限流可以看做是一种特殊的流量控制，仅对包含热点参数的资源调用生效。BlockException源码
      #参数例外项   普通版   超过1秒钟一个后，达到阈值后马上被限流
      #             期望    例如当p1的值为500的时候，不被限流或者限流阈值为其它，其余会被正常的阈值限流
      #参数的例外项类型必须为String或基本数据类型
      #如果手动在方法中添加异常，则不会被blockHandler异常处理

#系统规则   从整体维度对入口流量的控制
      #LOAD     仅对Linux和Unix系统有效，系统的load1作为判断指标，进行自适应保护。当load1超过启发值，且系统当前的并发线程数超过估算的系统容量时才会触发系统保护BBR，系统容量由maxQPS*minRT得出，设定的参考值为CPU cores*2.5
      #平均RT   单台机器所有入口流量的平均RT达到阈值即触发系统保护，单位是毫秒
      #线程数   单台机器所有入口流量的并发线程数达到阈值时触发系统保护
      #入口QPS  单台机器所有入口流量的QPS达到阈值时触发系统保护
      #CPU的使用率  CPU利用率超过设定的阈值时，则会触发系统保护


#注意点
    #当未做持久化规则处理时，资源服务停止后，限流规则自动消失，生产规则需要进行持久化配置到Nacos
       #（1）引入sentinel-datasource-nacos
       # (2)yml添加sentinel的数据源
    #默认每个sentinelResource都需要配置blockHandler，耦合性较高，需要创建自定义公共BlockHandler统一处理。
    #SentinelResource不能用于private方法
    #Sentinel三个核心的API为
        #sphU定义资源
        #Tracer定义统计，线程数、QPS等
        #ContextUtil定义了上下文

#服务熔断  Sentinel代替Hystrix与Ribbon和OpenFeign整合实现服务熔断和负载。热部署对于Hystrix和Sentinel都不友好。
         #block限流配置违规异常，fallback为程序运行异常
