spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8081
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"